import React from 'react'
import MainLayout from '../layouts/MainLayout';


const HomePage = () => {
  return (
    <>
    <MainLayout>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas molestias quos ratione vero modi, illo nesciunt minus consequuntur sapiente odio ipsa placeat tempora, maiores alias perferendis atque quasi iste expedita!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora voluptatum sint quo odit placeat fugit vel repellat hic nesciunt exercitationem ea numquam dignissimos quos voluptatibus reiciendis neque ab eum earum maxime, sit dolor laboriosam obcaecati sequi non! Dolores porro beatae labore quisquam accusantium nam placeat, esse cumque molestias corporis. Quae eveniet neque saepe dolore praesentium reiciendis quo assumenda dicta, laborum rem, minus error sunt! Explicabo asperiores similique doloribus aut fugit, debitis voluptatem cupiditate impedit assumenda temporibus consequatur veniam. Maiores nesciunt recusandae cumque dicta aperiam harum voluptate nam quod illum ipsam! Sit ducimus autem est debitis voluptatibus, ipsam non ratione consectetur nostrum vitae sint. A voluptatem atque excepturi fugiat, dicta laboriosam libero id. Blanditiis mollitia, sit provident maxime dolores excepturi fugiat quae aut minima animi sequi porro possimus quos voluptatum soluta saepe eveniet harum id. Esse, praesentium recusandae. Placeat dicta aperiam dolorum explicabo porro doloremque! Quo in eaque quia amet accusantium facilis natus aut eligendi doloremque, nisi alias commodi a sint tempore porro obcaecati! Sint expedita porro laborum, sapiente corrupti optio hic aspernatur asperiores suscipit, cumque officia delectus pariatur, laudantium nisi dolore alias? Eum et, a eligendi asperiores id nulla tempora nobis possimus aliquid veritatis ad placeat obcaecati vel aut sapiente.
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora voluptatum sint quo odit placeat fugit vel repellat hic nesciunt exercitationem ea numquam dignissimos quos voluptatibus reiciendis neque ab eum earum maxime, sit dolor laboriosam obcaecati sequi non! Dolores porro beatae labore quisquam accusantium nam placeat, esse cumque molestias corporis. Quae eveniet neque saepe dolore praesentium reiciendis quo assumenda dicta, laborum rem, minus error sunt! Explicabo asperiores similique doloribus aut fugit, debitis voluptatem cupiditate impedit assumenda temporibus consequatur veniam. Maiores nesciunt recusandae cumque dicta aperiam harum voluptate nam quod illum ipsam! Sit ducimus autem est debitis voluptatibus, ipsam non ratione consectetur nostrum vitae sint. A voluptatem atque excepturi fugiat, dicta laboriosam libero id. Blanditiis mollitia, sit provident maxime dolores excepturi fugiat quae aut minima animi sequi porro possimus quos voluptatum soluta saepe eveniet harum id. Esse, praesentium recusandae. Placeat dicta aperiam dolorum explicabo porro doloremque! Quo in eaque quia amet accusantium facilis natus aut eligendi doloremque, nisi alias commodi a sint tempore porro obcaecati! Sint expedita porro laborum, sapiente corrupti optio hic aspernatur asperiores suscipit, cumque officia delectus pariatur, laudantium nisi dolore alias? Eum et, a eligendi asperiores id nulla tempora nobis possimus aliquid veritatis ad placeat obcaecati vel aut sapiente.
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora voluptatum sint quo odit placeat fugit vel repellat hic nesciunt exercitationem ea numquam dignissimos quos voluptatibus reiciendis neque ab eum earum maxime, sit dolor laboriosam obcaecati sequi non! Dolores porro beatae labore quisquam accusantium nam placeat, esse cumque molestias corporis. Quae eveniet neque saepe dolore praesentium reiciendis quo assumenda dicta, laborum rem, minus error sunt! Explicabo asperiores similique doloribus aut fugit, debitis voluptatem cupiditate impedit assumenda temporibus consequatur veniam. Maiores nesciunt recusandae cumque dicta aperiam harum voluptate nam quod illum ipsam! Sit ducimus autem est debitis voluptatibus, ipsam non ratione consectetur nostrum vitae sint. A voluptatem atque excepturi fugiat, dicta laboriosam libero id. Blanditiis mollitia, sit provident maxime dolores excepturi fugiat quae aut minima animi sequi porro possimus quos voluptatum soluta saepe eveniet harum id. Esse, praesentium recusandae. Placeat dicta aperiam dolorum explicabo porro doloremque! Quo in eaque quia amet accusantium facilis natus aut eligendi doloremque, nisi alias commodi a sint tempore porro obcaecati! Sint expedita porro laborum, sapiente corrupti optio hic aspernatur asperiores suscipit, cumque officia delectus pariatur, laudantium nisi dolore alias? Eum et, a eligendi asperiores id nulla tempora nobis possimus aliquid veritatis ad placeat obcaecati vel aut sapiente.
    </  MainLayout>
    </>
  )
}

export default HomePage